### ISSUE TITLE
Not detecting device big-red-button

### ISSUE THREAD

**Issue by yasharma** [miguelmota/big-red-button#2]
I have attached the device bigRedButton, but it not detecting the device.

Can you please exaplain why you hardcode the vendorId and productId, if i remove (7476,13) then it is thowing error
```javascript
 allDevices = HID.devices(7476,13);
```
Below Error
```javascript
Device Count:: 4
opening BigRedButton 0
/home/yash/big-red-button/node_modules/node-hid/nodehid.js:28
    this._raw = new (Function.prototype.bind.apply(binding.HID,
                ^

Error: cannot open device with path 0005:0002:00
    at Error (native)
    at new HID (/home/yash/big-red-button/node_modules/node-hid/nodehid.js:28:17)
    at new BigRedButton (/home/yash/big-red-button/node_modules/big-red-button/index.js:30:14)
    at Object.<anonymous> (/home/yash/big-red-button/index.js:8:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)

```
Can you please help with this ?

**Comment by miguelmota** [comment]
The error is coming from the [`node-hid`](https://github.com/node-hid/node-hid/issues/102) module. You can try asking on their issue board.

A similar question has been asked before, maybe it'll help you
https://github.com/node-hid/node-hid/issues/102

Thanks for reporting error
